# Generated by Django 3.2.13 on 2022-10-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('idade', models.CharField(max_length=2)),
                ('nivel', models.CharField(choices=[('S', 'SENIOR'), ('P', 'PLENO'), ('J', 'JUNIOR')], max_length=1)),
                ('formacao', models.CharField(max_length=50)),
                ('pix', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(max_length=14)),
            ],
        ),
    ]
