# Generated by Django 3.2.13 on 2022-11-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221123_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
