# Generated by Django 3.2.16 on 2023-01-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('address', models.CharField(max_length=55)),
                ('data_nas', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('area', models.CharField(choices=[('T', 'Tecnologia'), ('S', 'Segurança'), ('M', 'Musico')], max_length=1)),
                ('level', models.CharField(choices=[('P', 'Profissional'), ('I', 'iniciante'), ('J', 'Junior'), ('P', 'Pleno'), ('S', 'Senior')], max_length=1)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
