# Generated by Django 3.2.16 on 2023-01-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='link_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
