# Generated by Django 3.2.16 on 2023-01-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_worker_link_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='link_social',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
