# Generated by Django 3.2.16 on 2023-01-31 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('local', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourne', to='evento.show_tipo')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
